service: serverless-python-ping
provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, env:STAGE, 'development'}
  region: ${opt:region, 'eu-west-1'}
  memorySize: 128
  timeout: 30
  environment:
    STAGE: ${opt:stage, self:provider.stage}
    REGION: ${opt:region, self:provider.region}

package:
  exclude:
    - contrib/**
    - build/**
    - .eggs/**
    - .cache/**
    - serverless_python_ping.egg-info/**
    - node_modules/**
    - .serverless/**
    - deploy/**
    - tests/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    noDeploy:
      - pytest
      - boto3
      - botocore
      - docutils
      - jmespath
      - python-dateutil
      - s3transfer
      - six

functions:
  get_google:
    handler: serverless_python_ping.get_google
