version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.3
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test

  deploy:
    docker:
      - image: circleci/python:3.6.3
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install node
          command: |
            curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version
      - run:
          name: install serverless
          command: npm install serverless
      - run:
          name: install serverless plugins
          command: |
            ./node_modules/serverless/bin/serverless plugin install -n serverless-python-requirements
            npm install
      - run:
          name: deploy
          command: ./node_modules/serverless/bin/serverless deploy
      - run:
          name: verify
          command: ./node_modules/serverless/bin/serverless invoke --function get_google

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
